### ISSUE TITLE
Add locations with apple wallet

### ISSUE THREAD

**Issue by jozefbonnar** [sargant/dfyb.run#48]
Add locations with apple wallet so it shows up on the home screen when at the event location, I'm pretty sure you can access coordinates from the parkrun API but I'm not so sure. 
https://developer.apple.com/documentation/walletpasses/pass/locations

**Comment by sargant** [comment]
Thanks for using dfyb.run, and especially thanks for the feedback!

I've thought about this before and I'm probably not going to do this for a couple of reasons:

- The list of parkrun locations is very, very long, and changes all the time. There's no mechanism to update the list of locations associated with a pass, so this would lead to unexpected behaviour when visiting a parkrun that started after you downloaded your wallet pass.
- The pass would show all the time when you visited that location, regardless of day of the week. Doesn't make much sense on a Tuesday!

I have thought also about setting the pass to show up on a Saturday morning, but the Wallet spec doesn't let you specify a repeating schedule, just a singular date & time.

**Comment by jozefbonnar** [comment]
I understand the first part but that can be fixed by the user, you download all the locations initially, then have a GitHub automation every month to update it. Furthermore, on the site have a drop down menu with all the locations plus a manual mode where you can input your own location, linked in with the drop down you could have a google maps integration for an extra method to verify it’s the right location. It’s not the end of the world if it’s wrong since the pass will still operate normally. 

The second part, which I have just verified today, the pass only shows on your Lock Screen at that location, once you leave the pass then gets removed off your home screen. It doesn’t show all the time unless you are at that location.

**Comment by jozefbonnar** [comment]
@sargant
